#!/bin/bash -l
#PBS -l walltime=120:00:00
#PBS -l nodes=1:ppn=1
#PBS -N small_states_all
#PBS -e /gpfs/data/chin-lab/HRSA-FARA/Users/Manu/hrsa_max_feature_extraction/logs/small_states_all.err
#PBS -o /gpfs/data/chin-lab/HRSA-FARA/Users/Manu/hrsa_max_feature_extraction/logs/small_states_all.output
#PBS -l mem=9gb

module load gcc/6.2.0 miniconda3/4.7.10
conda activate /gpfs/data/chin-lab/HRSA-FARA/Users/Manu/pyenvs/py38
cd /gpfs/data/chin-lab/HRSA-FARA/Users/Manu/hrsa_max_feature_extraction/temp_scripts
python -u tiny_states_all.py